trailingComma: 'all'
tabWidth: 4
semi: false
singleQuote: true

overrides:
  - files: '*.js'
    options:
      semi: true
  - files:
      - '*.yml'
    options:
      tabWidth: 2
  - files:
      - '*.json'
    options:
      tabWidth: 2
      singleQuote: false
